import { ArchiveArtifact } from './types';

export const ARCHIVE_ARTIFACTS: ArchiveArtifact[] = [
  // ROOM 01: IMAGE
  {
    id: 'ARC-1974-008391',
    numericId: 8391,
    title: 'Monolith in Fog (Silver Gelatin)',
    year: '1974',
    category: 'IMAGE',
    roomId: 'image',
    maker: 'Unknown Maker',
    medium: 'Silver gelatin contact print on baryta fiber paper',
    dimensions: '180 × 240 cm',
    provenance: 'Acquired from the Estate of H. Lindqvist, Zurich',
    description: 'An architectural abstraction capturing raw brutalist concrete shrouded in maritime mist. The grain structure exhibits unique photochemical reticulation from sub-zero darkroom processing.',
    visualData: {
      aspectRatio: 1.33,
      colorPalette: ['#0d0e11', '#22252a', '#787d85', '#d4d8de', '#f5f0e8'],
      textureType: 'photograph',
      caption: 'FIG. 01 — DENSE EMBULSION STUDY',
    },
  },
  {
    id: 'ARC-1961-002194',
    numericId: 2194,
    title: 'Fragmented Façade with Parallax Shadows',
    year: '1961',
    category: 'IMAGE',
    roomId: 'image',
    maker: 'K. V. Sörensen',
    medium: 'High-contrast large-format negative',
    dimensions: '150 × 200 cm',
    provenance: 'Nordic Architectural Archive, Stockholm',
    description: 'A study of geometric modularity and cast sun shadows across a precast concrete monolith during the summer solstice in Oslo.',
    visualData: {
      aspectRatio: 1.5,
      colorPalette: ['#0a0a0a', '#1e1f22', '#595d66', '#aeb4bc', '#ffffff'],
      textureType: 'photograph',
      caption: 'FIG. 02 — SHADOW DISSECTION',
    },
  },
  {
    id: 'ARC-1983-009102',
    numericId: 9102,
    title: 'Translucent Membrane Study No. 4',
    year: '1983',
    category: 'IMAGE',
    roomId: 'image',
    maker: 'Elena Rostova',
    medium: 'Direct photogram on diazo film',
    dimensions: '210 × 160 cm',
    provenance: 'Private Collection, Leipzig',
    description: 'Layered industrial polymer films exposed to polarized ultraviolet illumination, revealing internal crystallographic strain lines.',
    visualData: {
      aspectRatio: 0.75,
      colorPalette: ['#121316', '#2b2d35', '#606470', '#c86432', '#f5f0e8'],
      textureType: 'photograph',
      caption: 'FIG. 03 — POLARIZED RESIN REFRACTION',
    },
  },

  // ROOM 02: SOUND
  {
    id: 'ARC-1958-001048',
    numericId: 1048,
    title: 'Poème Électronique Spatial Matrix',
    year: '1958',
    category: 'SOUND',
    roomId: 'sound',
    maker: 'E. Varèse / I. Xenakis',
    medium: '3-track magnetic tape with 425-loudspeaker routing schematic',
    dimensions: '480 seconds (spatial audio loop)',
    provenance: 'Philips Pavilion Archive, Brussels',
    description: 'A landmark concrete-acoustic spatial composition designed for asymmetric hyperbolic paraboloid chambers, blending machine hums, bells, and pure sinusoidal sweeps.',
    visualData: {
      aspectRatio: 1.0,
      colorPalette: ['#0f1013', '#c86432', '#d97d4c', '#e5e9ec'],
      textureType: 'waveform',
      caption: 'RESONANCE MATRIX: 425 CHANNELS',
    },
  },
  {
    id: 'ARC-1989-004291',
    numericId: 4291,
    title: 'Sub-Bass Resonator Harmonic 16Hz',
    year: '1989',
    category: 'SOUND',
    roomId: 'sound',
    maker: 'Institute for Acoustic Research',
    medium: 'Analog modular voltage-controlled oscillator array',
    dimensions: 'Continuous frequency continuum',
    provenance: 'Underground Sound Laboratory, Berlin',
    description: 'An infrasonic vibration study investigating architectural resonance thresholds and human tactile acoustic perception in solid granite chambers.',
    visualData: {
      aspectRatio: 1.2,
      colorPalette: ['#0a0b0d', '#181a20', '#3b404d', '#c86432'],
      textureType: 'waveform',
      caption: 'INFRASONIC FREQUENCY: 16.35 HZ',
    },
  },

  // ROOM 03: TYPOGRAPHY
  {
    id: 'ARC-1928-000412',
    numericId: 412,
    title: 'Die Neue Typographie Specimen Sheet',
    year: '1928',
    category: 'TYPE',
    roomId: 'typography',
    maker: 'Jan Tschichold',
    medium: 'Letterpress on unbleached rag paper',
    dimensions: '84 × 118 cm',
    provenance: 'Bauhaus Dessau Special Collections',
    description: 'The foundational manifesto asserting asymmetric layout, pure functional clarity, standardized DIN formats, and sans-serif monumental hierarchy.',
    visualData: {
      aspectRatio: 1.4,
      colorPalette: ['#0c0c0e', '#c86432', '#e5e9ec', '#f5f0e8'],
      textureType: 'typographic',
      glyph: 'FORM',
      caption: 'MONUMENTAL TYPE SPECIMEN',
    },
  },
  {
    id: 'ARC-1967-005619',
    numericId: 5619,
    title: 'Unigrid Spatial Grid System Matrix',
    year: '1967',
    category: 'TYPE',
    roomId: 'typography',
    maker: 'Massimo Vignelli',
    medium: 'Silkscreen and precision drafting mylar overlay',
    dimensions: '120 × 90 cm',
    provenance: 'Design Studies Collection, Milan',
    description: 'A rigorous modular layout framework orchestrating structural proportions, column mathematics, and typographic negative space.',
    visualData: {
      aspectRatio: 1.33,
      colorPalette: ['#101114', '#343842', '#8c93a0', '#ffffff'],
      textureType: 'typographic',
      glyph: 'LANGUAGE',
      caption: 'MODULAR PROPORTION SYSTEM',
    },
  },

  // ROOM 04: OBJECTS
  {
    id: 'ARC-1974-003310',
    numericId: 3310,
    title: 'Precision Rangefinder Camera Chassis',
    year: '1974',
    category: 'OBJECT',
    roomId: 'objects',
    maker: 'Ernst Leitz Optische Werke',
    medium: 'Milled magnesium alloy, vulcanite, brass gears',
    dimensions: '138 × 77 × 38 mm',
    provenance: 'Wetzlar Optical Heritage Trust',
    description: 'An iconic mechanical optical instrument capable of split-second manual range coincidence with micron-tolerance shutter escapements.',
    visualData: {
      aspectRatio: 1.0,
      colorPalette: ['#0d0e10', '#1c1e23', '#4a4f5c', '#b0b6c2', '#c86432'],
      textureType: 'blueprint',
      caption: 'OPTICAL CHASSIS: M4-P SPECIMEN',
    },
  },
  {
    id: 'ARC-1953-007820',
    numericId: 7820,
    title: 'Tubular Steel Cantilever Armchair Prototype',
    year: '1953',
    category: 'OBJECT',
    roomId: 'objects',
    maker: 'Marcel Breuer Studio',
    medium: 'Cold-bent chromium-plated steel tube, saddle hide',
    dimensions: '79 × 60 × 82 cm',
    provenance: 'Permanent Industrial Design Archive',
    description: 'A revolutionary structural exploration employing continuous bent aviation steel tubing to eliminate rear support legs entirely.',
    visualData: {
      aspectRatio: 1.0,
      colorPalette: ['#09090b', '#262930', '#636875', '#e5e9ec'],
      textureType: 'blueprint',
      caption: 'CONTINUOUS TUBE CANTILEVER',
    },
  },
  {
    id: 'ARC-1979-006155',
    numericId: 6155,
    title: 'Dual-Trace Analog Oscilloscope',
    year: '1979',
    category: 'OBJECT',
    roomId: 'objects',
    maker: 'Tektronix Laboratory Instruments',
    medium: 'Cathode-ray tube, bakelite rotary switches, brushed aluminum',
    dimensions: '32 × 18 × 44 cm',
    provenance: 'Acoustic Signal Processing Repository',
    description: 'An analog electronic testing instrument rendering real-time waveform phase, Lissajous figures, and signal voltages on a phosphor screen.',
    visualData: {
      aspectRatio: 1.0,
      colorPalette: ['#0b0d10', '#1a2228', '#2d634f', '#a4d4b4'],
      textureType: 'blueprint',
      caption: 'PHOSPHOR OSCILLOSCOPE MONITOR',
    },
  },

  // ROOM 05: FILM
  {
    id: 'ARC-1962-012847',
    numericId: 12847,
    title: 'La Jetée 35mm Celluloid Montage',
    year: '1962',
    category: 'FILM',
    roomId: 'film',
    maker: 'Chris Marker',
    medium: '35mm black-and-white safety film, optical mono soundtrack',
    dimensions: '28 minutes (2,520 feet)',
    provenance: 'Cinémathèque Française Preservation Vault',
    description: 'A legendary masterwork composed entirely of motionless photographic frames exploring time travel, catastrophic memory, and human fixation.',
    visualData: {
      aspectRatio: 1.66,
      colorPalette: ['#08080a', '#191a1d', '#52555e', '#a8adb8', '#ffffff'],
      textureType: 'celluloid',
      caption: 'FRAME NO. 1489 — PIER TERMINAL',
    },
  },

  // ROOM 06: DIGITAL
  {
    id: 'ARC-1984-019482',
    numericId: 19482,
    title: 'HyperCard Stack & Bitmapped GUI Archaeology',
    year: '1984',
    category: 'DIGITAL',
    roomId: 'digital',
    maker: 'Bill Atkinson / Apple Computer',
    medium: '1-bit monochrome bitmapped resource fork and binary stack',
    dimensions: '512 × 342 pixels (72 DPI)',
    provenance: 'Computer History Digital Archaeology Registry',
    description: 'The pioneering hypermedia software engine introducing point-and-click stacks, card navigation, and programmable graphical objects.',
    visualData: {
      aspectRatio: 1.5,
      colorPalette: ['#000000', '#1f2024', '#70747e', '#ffffff', '#c86432'],
      textureType: 'cybernetic',
      caption: '1-BIT MONOCHROME STACK RES',
    },
  },
];
